import importlib.machinery
import importlib.util
import io
import tempfile
import unittest
from contextlib import redirect_stdout
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MIGRATOR_PATH = ROOT / "tools" / "pc-devtasks-migrate-legacy"


def load_migrator_module():
    loader = importlib.machinery.SourceFileLoader(
        "pc_devtasks_migrate_legacy", str(MIGRATOR_PATH)
    )
    spec = importlib.util.spec_from_loader(loader.name, loader)
    module = importlib.util.module_from_spec(spec)
    loader.exec_module(module)
    return module


class TestPcDevtasksMigrateLegacy(unittest.TestCase):
    def setUp(self):
        self.migrator = load_migrator_module()

    def _feature_dev_tasks_path(self, root: Path, feature: str = "01-sample") -> Path:
        feature_dir = root / "docs" / "02-features" / feature
        feature_dir.mkdir(parents=True, exist_ok=True)
        return feature_dir / "dev-tasks.md"

    def _legacy_bootstrap_entry(self) -> str:
        return (
            "## Execution Log\n\n"
            "### WI-20260214-01 - Work item execution\n\n"
            "- Date: 2026-02-14\n"
            "- Scope / tasks covered: Bootstrap feature docs from PRD.\n"
            "- Planner: Codex\n"
            "- Patcher: Codex\n"
            "- Tester: Codex\n"
            "- Reporter: Codex\n"
            "- Outcome: pass\n"
            "- Tests run: none\n"
            "- Offload ids (if any): none\n"
            "- Docs/logs updated: feature docs\n"
            "- Notes: Initial hydration generated by `tools/prd-to-features`.\n\n"
            "## Task Breakdown\n"
        )

    def test_dry_run_reports_updates_without_writing_file(self):
        with tempfile.TemporaryDirectory() as tmp_dir:
            root = Path(tmp_dir)
            dev_tasks_path = self._feature_dev_tasks_path(root)
            original = self._legacy_bootstrap_entry()
            dev_tasks_path.write_text(original, encoding="utf-8")

            stdout = io.StringIO()
            with redirect_stdout(stdout):
                status = self.migrator.main(["--root", str(root), "--dry-run"])

            self.assertEqual(status, 0)
            self.assertIn("would update 1 file(s)", stdout.getvalue())
            self.assertEqual(dev_tasks_path.read_text(encoding="utf-8"), original)

    def test_apply_migrates_legacy_entry_to_completed_with_required_sections(self):
        with tempfile.TemporaryDirectory() as tmp_dir:
            root = Path(tmp_dir)
            dev_tasks_path = self._feature_dev_tasks_path(root)
            dev_tasks_path.write_text(self._legacy_bootstrap_entry(), encoding="utf-8")

            status = self.migrator.main(["--root", str(root)])

            self.assertEqual(status, 0)
            migrated = dev_tasks_path.read_text(encoding="utf-8")
            self.assertIn("- Outcome: completed", migrated)
            self.assertIn("#### Patch", migrated)
            self.assertIn("#### Final Report", migrated)

    def test_main_reports_no_legacy_entries_when_nothing_to_update(self):
        with tempfile.TemporaryDirectory() as tmp_dir:
            root = Path(tmp_dir)
            dev_tasks_path = self._feature_dev_tasks_path(root)
            dev_tasks_path.write_text(
                "## Execution Log\n\n- No runs yet.\n", encoding="utf-8"
            )

            stdout = io.StringIO()
            with redirect_stdout(stdout):
                status = self.migrator.main(["--root", str(root)])

            self.assertEqual(status, 0)
            self.assertIn("no legacy entries found", stdout.getvalue())


if __name__ == "__main__":
    unittest.main()
